<?php
namespace App\Services;
class ArtworkMatcherService {
 private const SERIES=['SRF-ELT'=>['type'=>'single','tokens'=>['SRF-ELT']],'ELT-S'=>['type'=>'single','tokens'=>['ELT-S']],'PSE'=>['type'=>'single','tokens'=>['PSN-ELT','PSE']],'SUP'=>['type'=>'single','tokens'=>['SUP']],'LUC'=>['type'=>'single','tokens'=>['LUC']],'CLV'=>['type'=>'single','tokens'=>['CLV']],'SRF'=>['type'=>'double','tokens'=>['SRF']],'CLT'=>['type'=>'double','tokens'=>['CLT']],'SNP'=>['type'=>'double','tokens'=>['SNP']],'PSN'=>['type'=>'double','tokens'=>['PSN']]];
 public function __construct(private GoogleDriveService $drive){}
 public function match(array $row,?array $index=null):array{$sku=strtoupper(trim((string)($row['sku']??'')));$product=trim((string)($row['product']??''));$variant=trim((string)($row['variant']??''));$series=$this->seriesFromSku($sku);$type=$series?(self::SERIES[$series]['type']??null):null;$design=$this->designCode($sku,$series);$color=$this->color($variant);if(stripos($product,'custom')!==false)return $this->out($series,$type,$product,$color,true,'CUSTOM',null,[]);if(!$series||!$type||!$design)return $this->out($series,$type,$product,$color,false,'MISSING',null,[]);$index??=$this->drive->artworkIndex();$ranked=[];foreach($index as $f){$score=$this->score($f,$series,$design,$color);if($score<=0)continue;$f['score']=$score;$f['reasons']=$color&&str_contains($this->norm($f['name']),$this->norm($color))?['series','design','color']:['series','design'];$f['side']=$this->side($f['name'],$type);$ranked[]=$f;}usort($ranked,fn($a,$b)=>$b['score']<=>$a['score']);if($type==='single'){$best=$ranked[0]??null;if(!$best||$best['score']<70)return $this->out($series,$type,$product,$color,false,'MISSING',null,[]);return $this->out($series,$type,$product,$color,false,'REVIEW',$this->confidence($best['score']),[$best]);}$front=collect($ranked)->first(fn($x)=>$x['side']==='front'&&$x['score']>=70);$back=collect($ranked)->first(fn($x)=>$x['side']==='back'&&$x['score']>=70);if(!$front||!$back)return $this->out($series,$type,$product,$color,false,'MISSING',null,array_values(array_filter([$front,$back])));return $this->out($series,$type,$product,$color,false,'REVIEW',$this->confidence(min($front['score'],$back['score'])),[$front,$back]);}
 public function seriesFromSku(?string $sku):?string{$sku=strtoupper((string)$sku);foreach(array_keys(self::SERIES) as $c)if(preg_match('/(?:^|-)'.preg_quote($c,'/').'(?:-|$)/',$sku))return $c;return null;}
 private function designCode(string $sku,?string $series):?string{if(!$sku||!$series)return null;$p=explode('-',$sku);array_shift($p);$tail=count(explode('-',$series))+1;if(count($p)<=$tail)return null;$d=array_slice($p,0,count($p)-$tail);return $d?implode('-',$d):null;}
 private function score(array $f,string $series,string $design,?string $color):int{$name=$this->norm(pathinfo($f['name'],PATHINFO_FILENAME));$path=$this->norm($f['path']??'');$hit=false;foreach(self::SERIES[$series]['tokens'] as $t)if(str_contains($name,$this->norm($t))||str_contains($path,$this->norm($t))){$hit=true;break;}if(!$hit||!str_contains($name,$this->norm($design)))return 0;$s=85;if($color&&str_contains($name,$this->norm($color)))$s+=15;return min(100,$s);}
 private function side(string $name,string $type):string{if($type==='single')return 'single';$n=$this->norm($name);if(preg_match('/(^|-)FRONT($|-)/',$n))return 'front';if(preg_match('/(^|-)BACK($|-)/',$n))return 'back';return 'unknown';}
 private function color(?string $v):?string{if(!$v)return null;$colors=['BLACK','WHITE','RED','NAVY','BLUE','ROYAL','GREEN','GOLD','TEAL','AQUA','PINK','ORANGE','GRAY','GREY','SILVER','CHARCOAL','NATURAL'];$v=strtoupper($v);foreach($colors as $c)if(preg_match('/\b'.preg_quote($c,'/').'\b/',$v))return $c;return null;}
 private function norm(string $v):string{return trim(preg_replace('/[^A-Z0-9]+/','-',strtoupper($v)),'-');}
 private function confidence(int $s):string{return $s>=95?'HIGH':($s>=80?'MEDIUM':'LOW');}
 private function out(?string $s,?string $t,string $d,?string $c,bool $custom,string $status,?string $conf,array $m):array{return ['series_code'=>$s,'design_type'=>$t,'design'=>strtoupper($d),'color'=>$c,'is_custom'=>$custom,'match_status'=>$status,'confidence'=>$conf,'matches'=>$m];}
}
