<?php
namespace App\Services;use App\Models\{ProductionItem,VerificationDecision,PrintBatch};use Illuminate\Support\Facades\DB;
class ProductionService{
 const YARDS=.143; const MATERIALS=['SUP'=>['Rave 9','Supreme 5'],'LUC'=>['Rave 8','Anchorage 5'],'CLV'=>['Rave 9','Lucky 5'],'ELT-S'=>['Rave 9','Viewmont 6'],'PSE'=>['Rave 9','Viewmont 6'],'SRF-ELT'=>['Rave 8','Malley 5'],'SRF'=>['Rave 8','Embry 5'],'CLT'=>['Rave 8','Rave 9'],'SNP'=>['Turbo 7','Rave 9'],'PSN'=>['Turbo 6','Rave 9']];
 function ids($i){return collect($i->matches??[])->pluck('id')->filter()->sort()->values()->all();}
 function current($i){$d=$i->decision;return $d&&$this->ids($i)===collect($d->drive_file_ids??[])->sort()->values()->all();}
 function ready($i){return !$i->is_custom&&$i->decision?->decision==='CORRECT'&&count($this->ids($i))&&$this->current($i);}
 function verify($i,$decision,$uid){abort_if($i->is_custom,422,'Custom artwork uses a separate approval journey.');$ids=$this->ids($i);abort_if(!$ids,422,'No Drive artwork available.');return VerificationDecision::updateOrCreate(['line_item_id'=>$i->line_item_id],['decision'=>$decision,'drive_file_ids'=>$ids,'updated_by'=>$uid]);}
 function queue(){return ProductionItem::with('decision')->get()->filter(fn($i)=>$this->ready($i))->values();}
 function summary($items){$p=[];$n=[];$sets=0;$sides=0;$files=0;foreach($items as $i){$q=$i->quantity;$sets+=$q;$r=self::MATERIALS[$i->series_code]??null;if(!$r)continue;$uses=$i->design_type==='single'?[[$r[0],1,$q],[$r[1],0,$q]]:[[$r[0],1,$q],[$r[1],1,$q]];$sides+=$i->design_type==='single'?$q:$q*2;$files+=$i->design_type==='single'?1:2;foreach($uses as [$m,$pr,$c]){if($pr){if(!isset($p[$m]))$p[$m]=['sides'=>0,'yards'=>0];$p[$m]['sides']+=$c;$p[$m]['yards']=round($p[$m]['yards']+$c*self::YARDS,3);}else{if(!isset($n[$m]))$n[$m]=['sides'=>0,'yards'=>0];$n[$m]['sides']+=$c;$n[$m]['yards']=round($n[$m]['yards']+$c*self::YARDS,3);}}}return ['approved_orders'=>$items->count(),'total_sets'=>$sets,'printable_sides'=>$sides,'artwork_files'=>$files,'printable_materials'=>$p,'nonprint_materials'=>$n,'total_yards'=>round(array_sum(array_column($p,'yards'))+array_sum(array_column($n,'yards')),3)];}
 function batch($uid){return DB::transaction(function()use($uid){$items=$this->queue();abort_if($items->isEmpty(),422,'No approved stock orders ready.');$orders=[];$fc=0;foreach($items as $i){$r=self::MATERIALS[$i->series_code]??null;if(!$r)continue;$ms=collect($i->matches??[]);$arts=[];if($i->design_type==='single'){$m=$ms->first();abort_if(!$m,422,'Single artwork missing.');$arts[]=$this->art('PRINT',$r[0],$m);$fc++;}else{$f=$ms->firstWhere('side','front');$b=$ms->firstWhere('side','back');abort_if(!$f||!$b,422,'Double artwork incomplete.');$arts[]=$this->art('FRONT',$r[0],$f);$arts[]=$this->art('BACK',$r[1],$b);$fc+=2;}$orders[]=['line_item_id'=>$i->line_item_id,'order'=>$i->order_number,'product'=>$i->product,'variant'=>$i->variant,'sku'=>$i->sku,'series_code'=>$i->series_code,'design_type'=>$i->design_type,'quantity'=>$i->quantity,'artworks'=>$arts];}$id='LB-BATCH-'.now('UTC')->format('Ymd-His').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,4));$payload=['batch_id'=>$id,'status'=>'QUEUED','created_at'=>now('UTC')->toIso8601String(),'yards_per_side_per_set'=>self::YARDS,'order_count'=>count($orders),'artwork_file_count'=>$fc,'orders'=>$orders];return PrintBatch::create(['batch_id'=>$id,'status'=>'QUEUED','order_count'=>count($orders),'artwork_file_count'=>$fc,'total_yards'=>$this->summary($items)['total_yards'],'payload'=>$payload,'created_by'=>$uid]);});}
 function art($s,$mat,$m){return ['side'=>$s,'material'=>$mat,'drive_file_id'=>$m['id']??null,'filename'=>$m['name']??null,'drive_link'=>$m['webViewLink']??null,'thumbnail'=>isset($m['id'])?'https://drive.google.com/thumbnail?id='.$m['id'].'&sz=w800':null];}
}
